### ISSUE TITLE
Status Code 403 & Terkena Captcha

### ISSUE THREAD

**Issue by diosamuel** [defrindr/brainly-scraper#11]
haii, result brainly error, sepertinya terkena captcha

ini kode saya

```javascript
const brainly = require('brainly-scraper')

brainly("nkri").then(res => {
	console.log(res);
});
```
![brainlycaptcha](https://user-images.githubusercontent.com/42204593/99179075-9bcf8b80-274c-11eb-95d6-50ef8ddd3601.jpg)

bagaimana ya solusinya?

**Comment by defrindr** [comment]
silahkan dicoba release terbaru mas,

**Comment by diosamuel** [comment]
> silahkan dicoba release terbaru mas,

baikk terimakasih mas
