### ISSUE TITLE
Mendapatkan jawaban 

### ISSUE THREAD

**Issue by fdciabdul** [defrindr/brainly-scraper#4]
saya rasa kurang lengkap jika pertanyaan saja , apa ada cara untuk mendapatkan jawaban nya ?

**Comment by fdciabdul** [comment]
Finally i found it 


```javascript
const brainly = require('brainly-scraper');


brainly(pertanyaan).then(res => {
        res.forEach(item => {
       console.log("---------------")
       console.log(item.pertanyaan)
 console.log(item.jawaban[0].text)
	
      console.log("----------------")
})
})

```

oiya , saat jalanin di VPS dengan IP beda country kok kena Block Captcha ya gan ?

**Comment by defrindr** [comment]
iya mas , masih nyari solusi nya ini supaya gak kena block.
kalo mas nya tau , mungkin bisa pull request

**Comment by hansputera** [comment]
> iya mas , masih nyari solusi nya ini supaya gak kena block.
> kalo mas nya tau , mungkin bisa pull request

Coba pakai proxy rotator gan, tapi proxy nya yang indonesia. saya sudah coba request pakai NPM request tanpa opsi proxy. Namun saya hanya dapat result 403. Mungkin coba saya tambahkan proxy indonesia agar bisa membuka blokir

**Comment by fdciabdul** [comment]
> > iya mas , masih nyari solusi nya ini supaya gak kena block.
> > kalo mas nya tau , mungkin bisa pull request
> 
> Coba pakai proxy rotator gan, tapi proxy nya yang indonesia. saya sudah coba request pakai NPM request tanpa opsi proxy. Namun saya hanya dapat result 403. Mungkin coba saya tambahkan proxy indonesia agar bisa membuka blokir

seperti nya bukan di proxy deh , tapi di request header nya

**Comment by hansputera** [comment]
coba aja dah

**Comment by fdciabdul** [comment]
> coba aja dah

masih gabisa wkwk

**Comment by hansputera** [comment]
help wanted gan:u

**Comment by hansputera** [comment]
Eh tapi btw kemarin gw coba request proxy di headers nya itu bisa cuman tertahan di **puppeteer**

**Comment by fdciabdul** [comment]
> Eh tapi btw kemarin gw coba request proxy di headers nya itu bisa cuman tertahan di **puppeteer**

mau bikin whatsapp bot bukan ?

**Comment by hansputera** [comment]
> > Eh tapi btw kemarin gw coba request proxy di headers nya itu bisa cuman tertahan di **puppeteer**
> 
> mau bikin whatsapp bot bukan ?

Bukan

**Comment by diosamuel** [comment]
> Eh tapi btw kemarin gw coba request proxy di headers nya itu bisa cuman tertahan di **puppeteer**

tertahan kyk gimana mas?

**Comment by hansputera** [comment]
> > Eh tapi btw kemarin gw coba request proxy di headers nya itu bisa cuman tertahan di **puppeteer**
> 
> tertahan kyk gimana mas?

Stuck disitu di puppeteer

**Comment by defrindr** [comment]
tadi saya coba looping request dari terminal sepertinya sudah tidak ada limitnya, bisa dilihat di [screenshot](https://i.ibb.co/jhG59vB/screenshot-25.png) ini, apa masih ada yang sering limit ??

**Comment by fdciabdul** [comment]
> tadi saya coba looping request dari terminal sepertinya sudah tidak ada limitnya, bisa dilihat di [screenshot](https://i.ibb.co/jhG59vB/screenshot-25.png) ( maaf kalau kurang jelas gambarnya) ini, apa masih ada yang sering limit ??

tetep ini kena block cors , atau pake corsanywhere aja om

**Comment by diosamuel** [comment]
> > > Eh tapi btw kemarin gw coba request proxy di headers nya itu bisa cuman tertahan di **puppeteer**
> > 
> > tertahan kyk gimana mas?
> 
> Stuck disitu di puppeteer
> 

bisa dishare screenshot stuck nya mas?

**Comment by defrindr** [comment]
> > tadi saya coba looping request dari terminal sepertinya sudah tidak ada limitnya, bisa dilihat di [screenshot](https://i.ibb.co/jhG59vB/screenshot-25.png) ( maaf kalau kurang jelas gambarnya) ini, apa masih ada yang sering limit ??
> 
> tetep ini kena block cors , atau pake corsanywhere aja om

mungkin bisa dicoba di local dulu mas,
saya coba jalankan script yang ada di photo normal, mas

[https://photos.app.goo.gl/RaK6ncDAuVEa4n9f6](https://photos.app.goo.gl/RaK6ncDAuVEa4n9f6)
