### ISSUE TITLE
terkena captcha ketika host di glitch, solusi ny apa ya?

### ISSUE THREAD

**Issue by KagChi** [defrindr/brainly-scraper#9]

**Comment by hansputera** [comment]
bisa dikirim screenshoot nya?

**Comment by KagChi** [comment]
https://bin.nezukochan.xyz/tagiridoqa

link hasteny aj :v

**Comment by KagChi** [comment]
mungkin harus pake proxy :v

**Comment by hansputera** [comment]
@defrindr glitch pakai ip us, jadi harus dibikin proxy rotate nya ga? Kayak deteksi platform nya ada di region mana. trs di get locate dan di rotate ke indonesia

**Comment by KagChi** [comment]
buat aja gan :v

**Comment by hansputera** [comment]
boleh, tapi bisanya saya pakai typescript doang

**Comment by KagChi** [comment]
hasil compile nya aja :v tar aing edit

**Comment by hansputera** [comment]
sisa pakai doang sih

**Comment by hansputera** [comment]
@defrindr izin buat versi typescriptnya

**Comment by KagChi** [comment]
itu blm di pakein proxy rotator?

**Comment by hansputera** [comment]
Belum, nanti saya tambahkan opsi proxy

**Comment by defrindr** [comment]
> @defrindr glitch pakai ip us, jadi harus dibikin proxy rotate nya ga? Kayak deteksi platform nya ada di region mana. trs di get locate dan di rotate ke indonesia

Iya mas, cuma work pakai ip Indonesia ini,

**Comment by defrindr** [comment]
> @defrindr izin buat versi typescriptnya

Iya kak, silahkan

**Comment by hansputera** [comment]
> > @defrindr izin buat versi typescriptnya
> 
> Iya kak, silahkan

Sudah gan sisa di review pull req nya

**Comment by KagChi** [comment]
dah lah ga ada yg bales
